name: macOS CI
on:
  push:
    branches:
      - main
jobs:
  osx-ci:
    name: OS X
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        os: [macos-11, macos-12,macos-13]
    
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew tap cozycactus/tap
        brew update
        brew install --HEAD librx888
        brew install soapysdr

    - name: Build
      run: |
        mkdir -p ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ github.workspace }}
        make

    - name: Install
      run: |
        cd ${{ github.workspace }}/build
        sudo make install
