name: macOS CI
on:
  push:
    branches:
      - main
jobs:
  osx-ci:
    name: OS X
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        config:
          - cc: gcc-10
            cxx: g++-10
            test_luajit: false
            os: macos-11
            python2_ver: '2.7'
            python3_ver: '3.8'
          - cc: gcc-11
            cxx: g++-11
            test_luajit: false
            os: macos-11
            python2_ver: '2.7'
            python3_ver: '3.8'
          - cc: clang
            cxx: clang++
            test_luajit: true
            os: macos-11
            python2_ver: '2.7'
            python3_ver: '3.8'
          - cc: clang
            cxx: clang++
            os: macos-12
            python2_ver: '2.7'
            python3_ver: '3.9'
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
      INSTALL_PREFIX: /usr/local
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew tap cozycactus/tap
        brew update
        brew install --HEAD librx888
        brew install soapysdr

    - name: Build
      run: |
        mkdir -p ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ github.workspace }}
        make

    - name: Install
      run: |
        cd ${{ github.workspace }}/build
        sudo make install
