name: macOS

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: List all installed brew packages
        run: |
          brew list
    
